SELECT B.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC;

# SELECT BOOK_ID, SALES_DATE, SUM(SALES) AS SALES_CNT
# FROM BOOK_SALES AS S
# WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
# GROUP BY BOOK_ID
# ORDER BY BOOK_ID;

# SELECT * FROM AUTHOR
# SELECT * FROM BOOK
# SELECT * FROM BOOK_SALES;