SELECT
    P.PRODUCT_CODE,
    O.SALES_A * P.PRICE AS SALES
FROM PRODUCT P
JOIN (
    SELECT
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS SALES_A
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS O ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE;