SELECT
    SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM 
    (SELECT
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT,
        SALES_DATE
    FROM ONLINE_SALE N
    UNION
    SELECT 
        PRODUCT_ID,
        NULL AS USER_ID,
        SALES_AMOUNT,
        SALES_DATE
    FROM OFFLINE_SALE F) AS A
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;