SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    C.DAILY_FEE*30*(1 - P.DISCOUNT_RATE*0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT
        CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    WHERE DURATION_TYPE = '30일 이상'
) AS P ON P.CAR_TYPE = C.CAR_TYPE
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV') AND
    (C.DAILY_FEE*30*(1 - P.DISCOUNT_RATE*0.01) BETWEEN 500000 AND 1999999) AND
    NOT EXISTS (
        SELECT R.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
        WHERE R.CAR_ID = C.CAR_ID AND
        (R.START_DATE <= '2022-11-30' AND R.END_DATE >= '2022-11-01')
    )
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;