SELECT
    R.FOOD_TYPE,
    R.REST_ID,
    R.REST_NAME,
    R.FAVORITES
FROM REST_INFO R
JOIN (
    SELECT I.FOOD_TYPE, MAX(I.FAVORITES) AS FAVORITES
    FROM REST_INFO I
    GROUP BY I.FOOD_TYPE
) AS G
ON G.FOOD_TYPE = R.FOOD_TYPE AND R.FAVORITES = G.FAVORITES
ORDER BY R.FOOD_TYPE DESC;
