SELECT
    I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, S.F AS SCORE
FROM REST_INFO I
JOIN (
    SELECT
        REST_ID,
        ROUND(AVG(REVIEW_SCORE), 2) AS F
    FROM REST_REVIEW
    GROUP BY REST_ID
) AS S ON S.REST_ID = I.REST_ID
WHERE ADDRESS LIKE "서울%"
ORDER BY S.F DESC, FAVORITES DESC;