SELECT CAR_ID, IF(sum(IF(END_DATE >= '2022-10-16' and START_DATE <= '2022-10-16', 1, 0)) > 0, '대여중', '대여 가능') as AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    ORDER BY CAR_ID DESC, END_DATE DESC