SELECT
    IF(MONTH(DIFFERENTIATION_DATE) <= 3, '1Q', 
       IF(MONTH(DIFFERENTIATION_DATE) <= 6, '2Q',
          IF(MONTH(DIFFERENTIATION_DATE) <= 9, '3Q', '4Q')
         )
      ) AS QUARTER,
    COUNT(*) AS EOCLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER;