SELECT
    F.FLAVOR
FROM FIRST_HALF F
JOIN (
    SELECT
        FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
) AS T
ON F.FLAVOR = T.FLAVOR
ORDER BY T.TOTAL + F.TOTAL_ORDER DESC
LIMIT 3;