SELECT
    A.APNT_NO,
    P.PT_NAME,
    P.PT_NO,
    A.MCDP_CD,
    D.DR_NAME,
    A.APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
JOIN PATIENT P ON P.PT_NO = A.PT_NO
WHERE
    A.MCDP_CD = 'CS' AND
    A.APNT_CNCL_YN = 'N' AND
    DATE(A.APNT_YMD) = '2022-04-13'
ORDER BY A.APNT_YMD;