SELECT DISTINCT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM DEVELOPERS D
JOIN (
    SELECT
        CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End') AS S
WHERE S.CODE & D.SKILL_CODE = S.CODE
ORDER BY D.ID;