SELECT
    U.USER_ID, U.NICKNAME, D.TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (
    SELECT
        WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD B
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
) AS D ON D.WRITER_ID = U.USER_ID
ORDER BY D.TOTAL_SALES;