SELECT
    P.MEMBER_NAME,
    V.REVIEW_TEXT,
    V.REVIEW_DATE
FROM REST_REVIEW V
JOIN (
    SELECT
        MEMBER_ID,
        COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC
    LIMIT 1
) AS R ON R.MEMBER_ID = V.MEMBER_ID
JOIN MEMBER_PROFILE P ON V.MEMBER_ID = P.MEMBER_ID
ORDER BY V.REVIEW_DATE, V.REVIEW_TEXT;