SELECT
    CAST(MID(H.START_DATE, 6, 2) AS SIGNED) AS MONTH,
    H.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE (START_DATE BETWEEN '2022-08-01' AND '2022-10-31') AND
    H.CAR_ID IN (
        SELECT
            CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    )
GROUP BY MONTH, H.CAR_ID
ORDER BY MONTH, H.CAR_ID DESC;