SELECT DISTINCT
    D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN (
    SELECT
        CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
) AS S ON D.SKILL_CODE & S.CODE = S.CODE
ORDER BY D.ID;