SELECT
    YEAR(D.DIFFERENTIATION_DATE) AS YEAR,
    (M.MSIZE - D.SIZE_OF_COLONY) AS YEAR_DEV,
    D.ID AS ID
FROM ECOLI_DATA D
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MSIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS M ON M.YEAR = YEAR(D.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;