# SELECT *
# FROM FIRST_HALF F
# JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
# WHERE INGREDIENT_TYPE = 'fruit_based'
# GROUP BY F.FLAVOR
# ORDER BY SUM(TOTAL_ORDER) DESC;

SELECT I.FLAVOR
FROM ICECREAM_INFO I
JOIN FIRST_HALF F ON F.FLAVOR = I.FLAVOR
WHERE INGREDIENT_TYPE = 'fruit_based' AND TOTAL_ORDER > 3000
GROUP BY F.FLAVOR
ORDER BY TOTAL_ORDER DESC;
