SELECT DISTINCT R.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS R
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON R.CAR_ID = H.CAR_ID
WHERE R.CAR_TYPE = '세단'
    AND START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY R.CAR_ID DESC;
    