SELECT
    SUM(SCORE) AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES E
JOIN HR_DEPARTMENT D ON D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE G ON G.EMP_NO = E.EMP_NO
GROUP BY E.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;