SELECT
    CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F
WHERE F.BOARD_ID = (
    SELECT B.BOARD_ID
    FROM USED_GOODS_BOARD B
    WHERE B.VIEWS = (
        SELECT MAX(B.VIEWS)
        FROM USED_GOODS_BOARD B
    )
)
ORDER BY F.FILE_ID DESC;